name: CI Build

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths-ignore:
    - '.github/*.yml'
  pull_request:
    paths-ignore:
    - '.github/*.yml'

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: >-
    -Dorg.gradle.parallel=true

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        java: [ '8', '11', '17' ]
        include:
        - os: 'windows-latest'
          java: '8'
        - os: 'macos-latest'
          java: '8'
    name: JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build
      id: build
      run: |
        ./.github/scripts/build.sh
